#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generate procedural realistic waste meshes for Gazebo.

This script creates Gazebo-compatible model folders under:

  src/waste_sorting_gazebo/models/realistic_waste/

Generated models:

  waste_plastic_deformed_bottle
  waste_metal_crushed_can
  waste_paper_crumpled
  waste_glass_shard

Each model folder contains:

  model.config
  model.sdf
  meshes/<mesh>.obj

Why procedural?
  - No external 3D asset dependency.
  - Repository remains reproducible.
  - Different deformed waste-like shapes can be generated from code.
  - Useful for thesis/demo explanation.

Important:
  These are lightweight procedural approximations, not photorealistic scanned assets.
  They provide 3D form variation such as crushed, twisted, crumpled, and broken shapes.
"""

import math
import os
import random
from typing import List, Tuple


Vector3 = Tuple[float, float, float]
Face = Tuple[int, int, int]


PACKAGE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUTPUT_ROOT = os.path.join(PACKAGE_ROOT, "models", "realistic_waste")


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def write_obj(path: str, vertices: List[Vector3], faces: List[Face]) -> None:
    with open(path, "w") as f:
        f.write("# Procedural realistic waste mesh\n")
        f.write("# Generated by generate_realistic_waste_meshes.py\n\n")

        for x, y, z in vertices:
            f.write("v {:.6f} {:.6f} {:.6f}\n".format(x, y, z))

        f.write("\n")

        # OBJ indices are 1-based.
        for a, b, c in faces:
            f.write("f {} {} {}\n".format(a + 1, b + 1, c + 1))


def write_model_config(model_dir: str, model_name: str, description: str) -> None:
    path = os.path.join(model_dir, "model.config")

    content = """<?xml version="1.0"?>
<model>
  <name>{model_name}</name>
  <version>1.0</version>
  <sdf version="1.6">model.sdf</sdf>
  <author>
    <name>Waste Sorting Robot Project</name>
    <email>none</email>
  </author>
  <description>{description}</description>
</model>
""".format(
        model_name=model_name,
        description=description,
    )

    with open(path, "w") as f:
        f.write(content)


def write_model_sdf(
    model_dir: str,
    model_name: str,
    mesh_filename: str,
    rgba: Tuple[float, float, float, float],
    mass: float,
    collision_box: Tuple[float, float, float],
) -> None:
    path = os.path.join(model_dir, "model.sdf")

    r, g, b, a = rgba
    sx, sy, sz = collision_box

    content = """<?xml version="1.0"?>
<sdf version="1.6">
  <model name="{model_name}">
    <static>false</static>
    <allow_auto_disable>false</allow_auto_disable>

    <link name="link">
      <pose>0 0 0 0 0 0</pose>

      <inertial>
        <mass>{mass}</mass>
        <inertia>
          <ixx>0.0008</ixx>
          <iyy>0.0008</iyy>
          <izz>0.0008</izz>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyz>0</iyz>
        </inertia>
      </inertial>

      <!--
        Simplified collision is used for stability.
        Visual mesh gives realistic shape, collision box keeps Gazebo physics robust.
      -->
      <collision name="collision">
        <geometry>
          <box>
            <size>{sx} {sy} {sz}</size>
          </box>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>8.0</mu>
              <mu2>8.0</mu2>
            </ode>
          </friction>
        </surface>
      </collision>

      <visual name="visual">
        <geometry>
          <mesh>
            <uri>model://realistic_waste/{model_name}/meshes/{mesh_filename}</uri>
            <scale>1 1 1</scale>
          </mesh>
        </geometry>
        <material>
          <ambient>{r} {g} {b} {a}</ambient>
          <diffuse>{r} {g} {b} {a}</diffuse>
          <specular>0.15 0.15 0.15 1</specular>
        </material>
      </visual>
    </link>
  </model>
</sdf>
""".format(
        model_name=model_name,
        mesh_filename=mesh_filename,
        mass=mass,
        sx=sx,
        sy=sy,
        sz=sz,
        r=r,
        g=g,
        b=b,
        a=a,
    )

    with open(path, "w") as f:
        f.write(content)


def add_quad(faces: List[Face], a: int, b: int, c: int, d: int) -> None:
    faces.append((a, b, c))
    faces.append((a, c, d))


def generate_deformed_cylinder(
    radius: float,
    height: float,
    segments: int,
    rings: int,
    crush_strength: float,
    twist_strength: float,
    noise_strength: float,
) -> Tuple[List[Vector3], List[Face]]:
    """
    Generates a deformed cylinder-like mesh.

    Used for:
      - plastic deformed bottle
      - metal crushed can
    """

    vertices: List[Vector3] = []
    faces: List[Face] = []

    for i in range(rings + 1):
        z_norm = i / float(rings)
        z = -height / 2.0 + z_norm * height

        # Radius changes along height to create bottle/can deformation.
        neck_factor = 1.0
        if z_norm > 0.72:
            neck_factor = 1.0 - 0.35 * ((z_norm - 0.72) / 0.28)

        local_crush_x = 1.0 + crush_strength * math.sin(2.0 * math.pi * z_norm + 0.8)
        local_crush_y = 1.0 - crush_strength * math.sin(2.0 * math.pi * z_norm + 0.8)

        twist = twist_strength * z_norm * math.pi

        for j in range(segments):
            theta = 2.0 * math.pi * j / float(segments)
            theta_twisted = theta + twist

            noise = 1.0 + random.uniform(-noise_strength, noise_strength)

            x = radius * neck_factor * local_crush_x * math.cos(theta_twisted) * noise
            y = radius * neck_factor * local_crush_y * math.sin(theta_twisted) * noise

            # Add dent waves.
            dent = 1.0 + 0.08 * math.sin(5.0 * theta + 8.0 * z_norm)
            x *= dent
            y *= dent

            vertices.append((x, y, z))

    # Side faces.
    for i in range(rings):
        for j in range(segments):
            a = i * segments + j
            b = i * segments + ((j + 1) % segments)
            c = (i + 1) * segments + ((j + 1) % segments)
            d = (i + 1) * segments + j
            add_quad(faces, a, b, c, d)

    # Bottom cap.
    bottom_center_index = len(vertices)
    vertices.append((0.0, 0.0, -height / 2.0))

    for j in range(segments):
        a = j
        b = (j + 1) % segments
        faces.append((bottom_center_index, b, a))

    # Top cap.
    top_center_index = len(vertices)
    vertices.append((0.0, 0.0, height / 2.0))

    top_start = rings * segments
    for j in range(segments):
        a = top_start + j
        b = top_start + ((j + 1) % segments)
        faces.append((top_center_index, a, b))

    return vertices, faces


def generate_crumpled_paper(
    width: float,
    height: float,
    grid_x: int,
    grid_y: int,
    amplitude: float,
) -> Tuple[List[Vector3], List[Face]]:
    """
    Generates a crumpled sheet-like mesh.

    Shape:
      - irregular rectangular paper
      - wavy z deformation
      - torn/jittered border
    """

    vertices: List[Vector3] = []
    faces: List[Face] = []

    for iy in range(grid_y + 1):
        y_norm = iy / float(grid_y)
        for ix in range(grid_x + 1):
            x_norm = ix / float(grid_x)

            x = -width / 2.0 + x_norm * width
            y = -height / 2.0 + y_norm * height

            border = ix == 0 or iy == 0 or ix == grid_x or iy == grid_y

            if border:
                x += random.uniform(-0.025, 0.025)
                y += random.uniform(-0.025, 0.025)

            z = amplitude * (
                0.7 * math.sin(4.0 * math.pi * x_norm)
                + 0.5 * math.sin(5.0 * math.pi * y_norm + 0.7)
                + 0.4 * math.sin(3.0 * math.pi * (x_norm + y_norm))
            )

            z += random.uniform(-amplitude * 0.25, amplitude * 0.25)

            vertices.append((x, y, z))

    row_len = grid_x + 1

    for iy in range(grid_y):
        for ix in range(grid_x):
            a = iy * row_len + ix
            b = iy * row_len + ix + 1
            c = (iy + 1) * row_len + ix + 1
            d = (iy + 1) * row_len + ix
            add_quad(faces, a, b, c, d)

    return vertices, faces


def generate_glass_shard(
    radius: float,
    points: int,
    thickness: float,
) -> Tuple[List[Vector3], List[Face]]:
    """
    Generates an irregular broken glass shard.

    Shape:
      - random polygon top
      - random polygon bottom
      - thin thickness
    """

    vertices: List[Vector3] = []
    faces: List[Face] = []

    polygon: List[Tuple[float, float]] = []

    for i in range(points):
        theta = 2.0 * math.pi * i / float(points)
        r = radius * random.uniform(0.45, 1.0)

        # Elongate shape slightly.
        x = r * math.cos(theta) * random.uniform(0.8, 1.35)
        y = r * math.sin(theta) * random.uniform(0.55, 1.0)

        polygon.append((x, y))

    # Top vertices.
    for x, y in polygon:
        z = thickness / 2.0 + random.uniform(-thickness * 0.15, thickness * 0.15)
        vertices.append((x, y, z))

    # Bottom vertices.
    for x, y in polygon:
        z = -thickness / 2.0 + random.uniform(-thickness * 0.15, thickness * 0.15)
        vertices.append((x, y, z))

    top_center = len(vertices)
    vertices.append((0.0, 0.0, thickness / 2.0))

    bottom_center = len(vertices)
    vertices.append((0.0, 0.0, -thickness / 2.0))

    # Top faces.
    for i in range(points):
        a = i
        b = (i + 1) % points
        faces.append((top_center, a, b))

    # Bottom faces.
    for i in range(points):
        a = points + i
        b = points + ((i + 1) % points)
        faces.append((bottom_center, b, a))

    # Side faces.
    for i in range(points):
        a = i
        b = (i + 1) % points
        c = points + ((i + 1) % points)
        d = points + i
        add_quad(faces, a, b, c, d)

    return vertices, faces


def create_model(
    model_name: str,
    mesh_name: str,
    vertices: List[Vector3],
    faces: List[Face],
    rgba: Tuple[float, float, float, float],
    mass: float,
    collision_box: Tuple[float, float, float],
    description: str,
) -> None:
    model_dir = os.path.join(OUTPUT_ROOT, model_name)
    meshes_dir = os.path.join(model_dir, "meshes")

    ensure_dir(meshes_dir)

    mesh_path = os.path.join(meshes_dir, mesh_name)

    write_obj(mesh_path, vertices, faces)
    write_model_config(model_dir, model_name, description)
    write_model_sdf(
        model_dir=model_dir,
        model_name=model_name,
        mesh_filename=mesh_name,
        rgba=rgba,
        mass=mass,
        collision_box=collision_box,
    )

    print("[OK] Generated model:", model_name)
    print("     mesh:", mesh_path)


def main() -> None:
    random.seed(42)

    ensure_dir(OUTPUT_ROOT)

    print("=" * 80)
    print("Generating realistic procedural waste models")
    print("Output:", OUTPUT_ROOT)
    print("=" * 80)

    # 1. Deformed plastic bottle.
    plastic_vertices, plastic_faces = generate_deformed_cylinder(
        radius=0.055,
        height=0.22,
        segments=28,
        rings=16,
        crush_strength=0.22,
        twist_strength=0.65,
        noise_strength=0.08,
    )

    create_model(
        model_name="waste_plastic_deformed_bottle",
        mesh_name="plastic_deformed_bottle.obj",
        vertices=plastic_vertices,
        faces=plastic_faces,
        rgba=(0.10, 0.35, 1.00, 1.0),
        mass=0.06,
        collision_box=(0.16, 0.13, 0.23),
        description="Procedural deformed plastic bottle-like waste object.",
    )

    # 2. Crushed metal can.
    metal_vertices, metal_faces = generate_deformed_cylinder(
        radius=0.06,
        height=0.13,
        segments=30,
        rings=10,
        crush_strength=0.35,
        twist_strength=0.25,
        noise_strength=0.10,
    )

    create_model(
        model_name="waste_metal_crushed_can",
        mesh_name="metal_crushed_can.obj",
        vertices=metal_vertices,
        faces=metal_faces,
        rgba=(0.72, 0.72, 0.72, 1.0),
        mass=0.09,
        collision_box=(0.16, 0.15, 0.14),
        description="Procedural crushed metal can-like waste object.",
    )

    # 3. Crumpled paper.
    paper_vertices, paper_faces = generate_crumpled_paper(
        width=0.28,
        height=0.20,
        grid_x=14,
        grid_y=10,
        amplitude=0.025,
    )

    create_model(
        model_name="waste_paper_crumpled",
        mesh_name="paper_crumpled.obj",
        vertices=paper_vertices,
        faces=paper_faces,
        rgba=(0.92, 0.82, 0.55, 1.0),
        mass=0.025,
        collision_box=(0.30, 0.22, 0.04),
        description="Procedural crumpled and torn paper-like waste object.",
    )

    # 4. Broken glass shard.
    glass_vertices, glass_faces = generate_glass_shard(
        radius=0.13,
        points=9,
        thickness=0.018,
    )

    create_model(
        model_name="waste_glass_shard",
        mesh_name="glass_shard.obj",
        vertices=glass_vertices,
        faces=glass_faces,
        rgba=(0.45, 0.90, 1.00, 0.55),
        mass=0.05,
        collision_box=(0.23, 0.18, 0.035),
        description="Procedural broken glass shard-like waste object.",
    )

    print("=" * 80)
    print("Done.")
    print("=" * 80)


if __name__ == "__main__":
    main()
